AllCops:
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Style/Documentation:
  Exclude:
    - db/migrate/*.rb

Style/FrozenStringLiteralComment:
  Enabled: false
  Exclude:
    - '.pryrc'